# Generated by Django 2.1.2 on 2019-06-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0006_auto_20190629_0334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(default='static/img/default-product.png', upload_to=''),
        ),
    ]
