# Generated by Django 2.1.2 on 2019-06-29 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0007_auto_20190629_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.FileField(upload_to=''),
        ),
    ]
